name: Michael Chwastiak
favicon: null
layout_spectrum: 0.06482600467279553
typography_spectrum: 0.7213301814626902
title: 'Michael Chwastiak: Producer, Actor, Writer.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121411'
    - '#746e6e'
    - '#303940'
    - '#4c555a'
    - '#9ba4a1'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
